# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Medicamentalia
email: raul@civio.es
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://medicamentalia.org" # the base hostname & protocol for your site

index:
  en: index.html
  es: index.es.html

# Collections
collections:
  articles:
    output: true
    permalink: /:categories/:slug/

# Defaults
defaults:
- scope:
    path: ""
  values:
    lang: "es"
- scope:
    path: ""
    type: "articles"
  values:
    layout: "article"

analytics_id: UA-28946840-11

fb_id: 620090684758872

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false

# Include files
include: 
- _pages

# Exclude files
exclude:
- _app
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- rollup-entry.js
- rollup.config.js
- README*
- ".gitignore"
- "fabfile.py"
- "fabfile.pyc"